"""initial schema

Revision ID: 628561ba9379
Revises: 
Create Date: 2026-02-22 23:40:30.188724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628561ba9379'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_fisico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('INICIAL', 'MENSUAL', 'ANUAL', name='inventariofisicotipoenum'), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'APLICADO', name='inventariofisicoestadoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('LIBRE', 'OCUPADA', name='mesaestadoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('platillo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('unidad', sa.String(length=32), nullable=False),
    sa.Column('stock_actual', sa.Float(), nullable=False),
    sa.Column('costo_promedio', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CAJERO', 'MESERO', 'COCINA', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('apertura_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monto_inicial', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTA', 'CERRADA', name='cajaestadoenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_fisico_det',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_fisico_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('conteo', sa.Float(), nullable=False),
    sa.Column('stock_sistema', sa.Float(), nullable=False),
    sa.Column('diferencia', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['inventario_fisico_id'], ['inventario_fisico.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('COMPRA', 'VENTA', 'MERMA', 'AJUSTE_POS', 'AJUSTE_NEG', name='movimientotipoenum'), nullable=False),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('saldo_cantidad', sa.Float(), nullable=False),
    sa.Column('costo_promedio_resultante', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'PREPARACION', 'SERVIDO', 'COBRADO', 'CANCELADO', name='pedidoestadoenum'), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesa.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platillo_ingrediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platillo_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_por_unidad', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['platillo_id'], ['platillo.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cierre_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apertura_caja_id', sa.Integer(), nullable=False),
    sa.Column('total_ventas', sa.Float(), nullable=False),
    sa.Column('total_efectivo', sa.Float(), nullable=False),
    sa.Column('total_tarjeta', sa.Float(), nullable=False),
    sa.Column('total_transferencia', sa.Float(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['apertura_caja_id'], ['apertura_caja.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apertura_caja_id')
    )
    op.create_table('cobro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('apertura_caja_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', name='cobrometodoenum'), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['apertura_caja_id'], ['apertura_caja.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id')
    )
    op.create_table('pedido_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('platillo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['platillo_id'], ['platillo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_detalle')
    op.drop_table('cobro')
    op.drop_table('cierre_caja')
    op.drop_table('platillo_ingrediente')
    op.drop_table('pedido')
    op.drop_table('movimiento_inventario')
    op.drop_table('inventario_fisico_det')
    op.drop_table('detalle_compra')
    op.drop_table('apertura_caja')
    op.drop_table('user')
    op.drop_table('producto')
    op.drop_table('platillo')
    op.drop_table('mesa')
    op.drop_table('inventario_fisico')
    op.drop_table('compra')
    # ### end Alembic commands ###
